# Generated by Django 4.0 on 2022-05-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('Condominium', 'Condominium'), ('HDB', 'HDB'), ('Landed', 'Landed')], default='HDB', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=7)),
                ('occupation_type', models.CharField(choices=[('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Employed', 'Employed')], default='Employed', max_length=10)),
                ('annual_income', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familymembers', to='api.household')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.familymember')),
            ],
        ),
    ]
